name: pulsar-io-bigquery integration tests

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Login to cloudsmith
      run: docker login -u="${{ secrets.CLOUDSMITH_USERNAME }}" -p="${{ secrets.CLOUDSMITH_API_KEY
        }}" docker.cloudsmith.io
      env:
        CLOUDSMITH_USERNAME: ${{ secrets.CLOUDSMITH_USERNAME }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    - uses: actions/checkout@v1
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: build
      run: mvn clean package -DskipTests

      env:
        CLOUDSMITH_USERNAME: ${{ secrets.CLOUDSMITH_USERNAME }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    - name: test
      uses: nick-invision/retry@v2
      env:
        BIG_QUERY_KEY: ${{ secrets.BIG_QUERY_KEY }}
      with:
        timeout_minutes: 60
        max_attempts: 1
        retry_on: error
        command: |
          echo $BIG_QUERY_KEY > ./.ci/integrations/bigquery-key.json
          ./.ci/integrations/run-integrations-test.sh
