name: pulsar-io-big-query unit tests

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to cloudsmith
      run: docker login -u="${{ secrets.CLOUDSMITH_USERNAME }}" -p="${{ secrets.CLOUDSMITH_API_KEY
        }}" docker.cloudsmith.io
      env:
        CLOUDSMITH_USERNAME: ${{ secrets.CLOUDSMITH_USERNAME }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: License check
      run: mvn license:check

      env:
        CLOUDSMITH_USERNAME: ${{ secrets.CLOUDSMITH_USERNAME }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    - name: Build with Maven skipTests
      run: mvn clean install -DskipTests

      env:
        CLOUDSMITH_USERNAME: ${{ secrets.CLOUDSMITH_USERNAME }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    - name: Style check
      run: mvn checkstyle:check

      env:
        CLOUDSMITH_USERNAME: ${{ secrets.CLOUDSMITH_USERNAME }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    - name: Spotbugs check
      run: mvn spotbugs:check

      env:
        CLOUDSMITH_USERNAME: ${{ secrets.CLOUDSMITH_USERNAME }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    - name: Run unit test
      run: mvn test -Dtest="*Test"  -DfailIfNoTests=false
      env:
        CLOUDSMITH_USERNAME: ${{ secrets.CLOUDSMITH_USERNAME }}
        CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
